project:
  type: website
  output-dir: _site

website:
  title: "OLC731 – R Yazılımı ile Ölçme Uygulamaları"
  navbar:
    left:
      - text: "📘 Tanıtım & İzlence"
        href: index.qmd
      - text: "📅 Haftalık İçerik"
        href: haftalar/index.qmd


  sidebar:
    - id: haftalar
      title: "Haftalık İçerik"
      style: docked
      contents:
        - haftalar/01_Giris.html
        - haftalar/02_Veri_duz.html
        - haftalar/03_Gorsel.html



format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 2
    number-sections: true
    code-fold: true

editor: visual
