<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Regresyon Modelleri – OLC731 – R Yazılımı ile Ölçme Uygulamaları</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-bce83624dd429190d13db9bf62533269.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<link href="../site_libs/pagedtable-1.1/css/pagedtable.css" rel="stylesheet">

<script src="../site_libs/pagedtable-1.1/js/pagedtable.js"></script>


  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-sidebar docked nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">OLC731 – R Yazılımı ile Ölçme Uygulamaları</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">📘 Tanıtım &amp; İzlence</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../haftalar/index.html"> 
<span class="menu-text">📅 Haftalık İçerik</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item">Regresyon Modelleri</li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
 <span class="menu-text">haftalar/01_Giris.html</span>
  </li>
        <li class="sidebar-item">
 <span class="menu-text">haftalar/02_Veri_duz.html</span>
  </li>
        <li class="sidebar-item">
 <span class="menu-text">haftalar/03_Gorsel.html</span>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul class="collapse">
  <li><a href="#en-küçük-kareler-prosedürünün-özellikleri" id="toc-en-küçük-kareler-prosedürünün-özellikleri" class="nav-link active" data-scroll-target="#en-küçük-kareler-prosedürünün-özellikleri"><span class="header-section-number">1</span> En Küçük Kareler Prosedürünün Özellikleri</a></li>
  <li><a href="#temel-kavramlar" id="toc-temel-kavramlar" class="nav-link" data-scroll-target="#temel-kavramlar"><span class="header-section-number">2</span> Temel Kavramlar</a></li>
  <li><a href="#regresyon-modellerini-yorumlama" id="toc-regresyon-modellerini-yorumlama" class="nav-link" data-scroll-target="#regresyon-modellerini-yorumlama"><span class="header-section-number">3</span> Regresyon Modellerini Yorumlama</a></li>
  <li><a href="#yorumlama-hataları" id="toc-yorumlama-hataları" class="nav-link" data-scroll-target="#yorumlama-hataları"><span class="header-section-number">4</span> 🚨 Yorumlama Hataları</a></li>
  <li><a href="#basit-lineer-modelleri-kurmak" id="toc-basit-lineer-modelleri-kurmak" class="nav-link" data-scroll-target="#basit-lineer-modelleri-kurmak"><span class="header-section-number">5</span> 🛠️ Basit Lineer Modelleri Kurmak</a></li>
  <li><a href="#model-uygunluğu" id="toc-model-uygunluğu" class="nav-link" data-scroll-target="#model-uygunluğu"><span class="header-section-number">6</span> Model Uygunluğu</a></li>
  <li><a href="#kaldıraç-leverage-ve-etki-influence" id="toc-kaldıraç-leverage-ve-etki-influence" class="nav-link" data-scroll-target="#kaldıraç-leverage-ve-etki-influence"><span class="header-section-number">7</span> Kaldıraç (Leverage) ve Etki (Influence)</a></li>
  <li><a href="#aykırı-değerlerle-başa-çıkma" id="toc-aykırı-değerlerle-başa-çıkma" class="nav-link" data-scroll-target="#aykırı-değerlerle-başa-çıkma"><span class="header-section-number">8</span> 🗑️ Aykırı Değerlerle Başa Çıkma</a></li>
  <li><a href="#model-uygunluklarını-karşılaştırma" id="toc-model-uygunluklarını-karşılaştırma" class="nav-link" data-scroll-target="#model-uygunluklarını-karşılaştırma"><span class="header-section-number">9</span> Model Uygunluklarını Karşılaştırma</a></li>
  <li><a href="#olağandışı-noktalar" id="toc-olağandışı-noktalar" class="nav-link" data-scroll-target="#olağandışı-noktalar"><span class="header-section-number">10</span> Olağandışı Noktalar</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Regresyon Modelleri</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(openintro)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>İstatistikte modeller çok yaygındır. Çoğu durumda, bağımlı değişkenimizin değerinin, bağımsız değişkenimizin bir fonksiyonu artı biraz rastgele hata olduğunu varsayarız.</p>
<p><span class="math display">\[
bagimli = f(bagimsiz) + hata
\]</span></p>
<p>Basit doğrusal regresyon modeli için, <span class="math inline">\(f\)</span>’nin basitçe <strong>doğrusal bir fonksiyon</strong> şeklini aldığını varsayarız. Böylece modelimiz, bağımlı değişkeninin değerini bir doğruyu oluşturan bileşenler (bir kesişim ve bir eğim) cinsinden tanımlar:</p>
<p><span class="math display">\[
bağımlı = kesisim + egim \cdot bagimsiz + hata
\]</span></p>
<p>Regresyon modelinde, <strong>populasyon parametrelerini</strong> temsil etmek için kesişim (<span class="math inline">\(\beta_0\)</span>) ve eğim (<span class="math inline">\(\beta_1\)</span>) için <strong>Yunan harfleri</strong> kullanırız.</p>
<p>Hata terimi genellikle <span class="math inline">\(\epsilon\)</span> ile gösterilir.</p>
<p><span class="math display">\[
Y = \beta_0 + \beta_1 \cdot X + \epsilon , \qquad \epsilon \sim N(0, \sigma_\epsilon)
\]</span></p>
<p>Verilerle populasyon regresyon denklemini tahmin ettiğimizde, kesişim ve eğim değerlerimizin gerçek populasyon parametrelerinin tahminleri olduğunu belirtmeliyiz.</p>
<p><span class="math inline">\(Y\)</span> yerine <span class="math inline">\(\mathbf{\hat{y}}\)</span> kullanılır (tahmin edilen ortalama tepki).</p>
<p>Hata terimleri (<span class="math inline">\(\epsilon\)</span>) kaldırılır (bireysel tepkileri değil, ortalama tepkiyi tahmin ediyoruz).</p>
<p><span class="math inline">\(\beta_0\)</span> yerine <span class="math inline">\(\mathbf{\widehat{\beta_0}}\)</span> (kesişim tahmini) kullanılır.</p>
<p><span class="math inline">\(\beta_1\)</span> yerine <span class="math inline">\(\mathbf{\widehat{\beta_1}}\)</span> (eğim tahmini) kullanılır.</p>
<p>Ortaya çıkan model:</p>
<p><span class="math display">\[
\hat{y} = \hat{\beta}_0 + \hat{\beta}_1 \cdot X
\]</span></p>
<p>Verilerde gözlemlenen değer (<span class="math inline">\(Y\)</span>) ile regresyon çizgisinden tahmin edilen değer (<span class="math inline">\(\hat{Y}\)</span>) arasındaki farka “<strong>artık</strong>” denir.</p>
<p><span class="math display">\[
e = Y - \hat{Y}
\]</span></p>
<ul>
<li><p>Regresyon çizgisinin üzerindeki gözlemler, tahmin edilen değerlerini aşmıştır ve <strong>pozitif artığa</strong> sahiptir.</p></li>
<li><p>Regresyon çizgisinin altındaki değerler, tahmin edilen değerlerinden küçüktür ve <strong>negatif artığa</strong> sahiptir.</p></li>
<li><p>Artıklar (<span class="math inline">\(e\)</span>), populasyon regresyon denklemindeki (<span class="math inline">\(\epsilon\)</span>) <strong>tahminleridir</strong>.</p></li>
</ul>
<section id="en-küçük-kareler-prosedürünün-özellikleri" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="en-küçük-kareler-prosedürünün-özellikleri"><span class="header-section-number">1</span> En Küçük Kareler Prosedürünün Özellikleri</h2>
<p>En küçük kareler prosedürü her zaman benzersiz bir çözüm bulur ve regresyon çizgisi her zaman şu iki özelliğe sahiptir:</p>
<ol type="1">
<li><p><strong>Artıkların toplamı her zaman 0’dır.</strong></p></li>
<li><p><strong>Ortalama nokta</strong> <span class="math inline">\((\bar{x}, \bar{y})\)</span> her zaman regresyon çizgisinin üzerindedir.</p></li>
</ol>
</section>
<section id="temel-kavramlar" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="temel-kavramlar"><span class="header-section-number">2</span> Temel Kavramlar</h2>
<ul>
<li><p><span class="math inline">\(\mathbf{\hat{Y}}\)</span>: Verilen bir <span class="math inline">\(X\)</span> değeri için tepkinin <strong>ortalama</strong> değeridir (en iyi tahminimiz).</p></li>
<li><p><span class="math inline">\(\mathbf{\hat{\beta}}\)</span>’lar: Gerçek, bilinmeyen <span class="math inline">\(\beta\)</span>’ların <strong>tahminleridir</strong>.</p></li>
<li><p><strong>Artıklar</strong> (<span class="math inline">\(e\)</span>’ler): Gerçek, bilinmeyen <strong>hatanın</strong> (<span class="math inline">\(\epsilon\)</span>’ler) tahminleridir.</p></li>
</ul>
<p>Aşağıdaki doğrusal regresyon modelini ele alalım:</p>
<p><span class="math display">\[
Y = \beta_0 + \beta_1 \cdot X + \epsilon , \epsilon \sim N(0, \sigma_{\epsilon}) ,.
\]</span> <strong>Eğim katsayısı</strong> <span class="math inline">\(\mathbf{\beta_1}\)</span> (bağımsız değişken <span class="math inline">\(X\)</span> ile çarpılan parametredir).</p>
<p>ABD eyaletlerindeki lise mezuniyet oranının (<span class="math inline">\(hs_{grad}\)</span>) bir fonksiyonu olarak yoksulluk oranı (<span class="math inline">\(poverty\)</span>) için tahmin edilen model:</p>
<p><span class="math display">\[\widehat{poverty} = 64.594 - 0.591 \cdot hs_{grad}\]</span></p>
<p>Hampshire County’de (Western Massachusetts) lise mezuniyet oranı %92.4’tür. Bu, Hampshire County’deki ortalama yoksulluk oranının ne olmasının beklendiği anlamına gelir?</p>
<p>Çözüm: <span class="math inline">\(hs_{grad}\)</span> yerine 92.4’ü koyarak <span class="math inline">\(\widehat{poverty}\)</span> değerini hesaplarız.</p>
<p><span class="math inline">\(\widehat{poverty} = 64.594 - 0.591 \cdot 92.4\)</span></p>
<p><span class="math inline">\(\widehat{poverty} \approx 64.594 - 54.608\)</span><span class="math inline">\(\widehat{poverty} \approx 9.986 \approx 10.0\%\)</span></p>
<p>Cevap: Yaklaşık %10.0 olması beklenmektedir (Beklenen değer olduğunu belirtmek önemlidir).</p>
<p>Basit doğrusal regresyon modelinin eğimi (<span class="math inline">\(b_1\)</span>) ve kesişimi (<span class="math inline">\(b_0\)</span>), temel özet istatistiklerden hesaplanabilir:Eğim (<span class="math inline">\(b_1\)</span>)<br>
</p>
<p><span class="math display">\[
b_1 = r_{x,y} \cdot \frac{s_y}{s_x}
\]</span></p>
<p><span class="math inline">\(r_{x,y}\)</span>: <span class="math inline">\(x\)</span> ve <span class="math inline">\(y\)</span>’nin korelasyonu (cor()).</p>
<p><span class="math inline">\(s_x, s_y\)</span>: <span class="math inline">\(x\)</span> ve <span class="math inline">\(y\)</span>’nin standart sapması (sd()).</p>
<ol start="2" type="1">
<li><strong>Kesişim (</strong><span class="math inline">\(b_0\)</span>): Ortalama nokta <span class="math inline">\((\bar{x}, \bar{y})\)</span> her zaman regresyon çizgisinin üzerindedir:</li>
</ol>
<p><span class="math display">\[
\bar{y} = b_0 + b_1 \cdot \bar{x} \implies b_0 = \bar{y} - b_1 \cdot \bar{x}
\]</span></p>
<p><code>midiPISA</code>veri setini ODOKUMA1 (<span class="math inline">\(y = ODOKUMA1\)</span>) ve OKUMAZZEVK (<span class="math inline">\(x = OKUMA_ZEVK\)</span>) için <span class="math inline">\(\mathbf{b_1}\)</span> eğimini ve <span class="math inline">\(\mathbf{b_0}\)</span> kesişimini bulun.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="st">"data/midiPISA.rda"</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>midiPISA <span class="ot">&lt;-</span> <span class="fu">na.omit</span>(midiPISA)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Aşağıdaki <code>bdims_summary</code> tablosu özet istatistikleri içermektedir:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>midiPISA_ozet <span class="ot">&lt;-</span> midiPISA <span class="sc">|&gt;</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">N =</span> <span class="fu">n</span>(), <span class="at">r =</span> <span class="fu">cor</span>(ODOKUMA1, OKUMA_ZEVK), </span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>            <span class="at">mean_ODOKUMA1 =</span> <span class="fu">mean</span>(ODOKUMA1), <span class="at">sd_ODOKUMA1 =</span> <span class="fu">sd</span>(ODOKUMA1), </span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">mean_OKUMA_ZEVK =</span> <span class="fu">mean</span>(OKUMA_ZEVK), <span class="at">sd_OKUMA_ZEVK =</span> <span class="fu">sd</span>(OKUMA_ZEVK))</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Tablonun içeriği:</span></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(midiPISA_ozet)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 1
Columns: 6
$ N               &lt;int&gt; 6655
$ r               &lt;dbl&gt; 0.2240121
$ mean_ODOKUMA1   &lt;dbl&gt; 466.3947
$ sd_ODOKUMA1     &lt;dbl&gt; 86.84393
$ mean_OKUMA_ZEVK &lt;dbl&gt; 0.6847341
$ sd_OKUMA_ZEVK   &lt;dbl&gt; 0.9752238</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(midiPISA_ozet)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 6
      N     r mean_ODOKUMA1 sd_ODOKUMA1 mean_OKUMA_ZEVK sd_OKUMA_ZEVK
  &lt;int&gt; &lt;dbl&gt;         &lt;dbl&gt;       &lt;dbl&gt;           &lt;dbl&gt;         &lt;dbl&gt;
1  6655 0.224          466.        86.8           0.685         0.975</code></pre>
</div>
</div>
<p>Şimdi, mutate() kullanarak slope (eğim) ve intercept (kesişim) sütunlarını ekleyelim.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>midiPISA_ozet <span class="sc">%&gt;%</span> </span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Eğim (slope) hesaplaması</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">egim =</span> r <span class="sc">*</span> sd_ODOKUMA1  <span class="sc">/</span> sd_OKUMA_ZEVK,</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Kesişim (intercept) hesaplaması: b0 = y_bar - b1 * x_bar</span></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">kesisim =</span> mean_ODOKUMA1 <span class="sc">-</span> egim <span class="sc">*</span> mean_OKUMA_ZEVK</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span>   <span class="fu">select</span>(kesisim, egim)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["kesisim"],"name":[1],"type":["dbl"],"align":["right"]},{"label":["egim"],"name":[2],"type":["dbl"],"align":["right"]}],"data":[{"1":"452.7354","2":"19.94834"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(midiPISA, <span class="at">formula =</span> ODOKUMA1 <span class="sc">~</span> OKUMA_ZEVK)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = ODOKUMA1 ~ OKUMA_ZEVK, data = midiPISA)

Coefficients:
(Intercept)   OKUMA_ZEVK  
     452.74        19.95  </code></pre>
</div>
</div>
</section>
<section id="regresyon-modellerini-yorumlama" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="regresyon-modellerini-yorumlama"><span class="header-section-number">3</span> Regresyon Modellerini Yorumlama</h2>
<p>UCLA’daki bazı rastgele seçilmiş dersler için gereken 73 ders kitabı hakkında veri toplanmıştır. Her kitabın <strong>UCLA kitapçısındaki</strong> (<code>ucla_new</code>) ve <strong>Amazon.com’daki</strong> (<code>amaz_new</code>) perakende fiyatları bilinmektedir.</p>
<blockquote class="blockquote">
<p>UCLA kitapçısındaki kitap fiyatlarıyla hangi faktörler ilişkilidir?</p>
</blockquote>
<p>Kitapların <strong>Amazon fiyatı</strong> (x) ile <strong>UCLA kitapçısı fiyatı</strong> (y) arasındaki ilişki güçlü, pozitif ve doğrusaldır.</p>
<p>Bu güçlü ilişki, regresyon modellemesi için iyi bir başlangıçtır.</p>
<p>Regresyon modelini <strong>R</strong>’da <code>lm()</code> fonksiyonu ile oluşturabiliriz:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(ucla_new <span class="sc">~</span> amaz_new, <span class="at">data =</span> textbooks)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = ucla_new ~ amaz_new, data = textbooks)

Coefficients:
(Intercept)     amaz_new  
      0.929        1.199  </code></pre>
</div>
</div>
<p>Çıktıdan elde edilen katsayılar:</p>
<ul>
<li><p><strong>Kesişim</strong> (<span class="math inline">\(\hat{\beta}_0\)</span>): $0.929</p></li>
<li><p><strong>Eğim</strong> (<span class="math inline">\(\hat{\beta}_1\)</span>): $1.199</p></li>
</ul>
<p>Tahmin edilen UCLA fiyatını <span class="math inline">\((\widehat{ucla_{new}})\)</span> Amazon fiyatı <span class="math inline">\((amazon_{new})\)</span> cinsinden ifade eden denklem şöyledir:</p>
<p><span class="math display">\[
\widehat{ucla\_{new}} = 0.929 + 1.199 \cdot amazon\_{new}
\]</span></p>
<p>(<span class="math inline">\(\hat{\beta}_1 = 1.199\)</span>)</p>
<p><strong>Yorum:</strong> Amazon’un bir kitap için talep ettiği fiyattaki <strong>her bir ek $1’lık artış için</strong>, UCLA kitapçısındaki kitapların <strong>ortalama fiyatının yaklaşık $1.20</strong> artması beklenir.</p>
<ul>
<li><p>Bu, ortalama olarak, UCLA kitapçısındaki kitap fiyatının Amazon’daki karşılık gelen fiyattan yaklaşık <strong>%20 daha yüksek</strong> olduğu anlamına gelir (<span class="math inline">\(1.20\)</span> katı).</p></li>
<li><p><strong>Unutmayın:</strong> Eğim, <strong>açıklayıcı değişkendeki bir birimlik değişikliğe karşılık, bağımlı değişkendeki (yanıt) tahmini ortalama değişimi</strong> gösterir.</p></li>
</ul>
<p>(<span class="math inline">\(\hat{\beta}_0 = 0.929\)</span>)</p>
<ul>
<li><strong>Yorum:</strong> Amazon’da <strong>$0</strong> olan bir kitabın, UCLA kitapçısında <strong>ortalama $0.93</strong>’a mal olması beklenir.</li>
</ul>
<p><strong>Dikkat:</strong> Bu değer, veri kümesindeki Amazon fiyatlarının aralığının <strong>dışında</strong> (en düşük fiyat $8.60’dı) olduğu için <strong>alakasızdır</strong> ve <strong>ekstrapolasyon</strong> (verinin aralığı dışındaki tahmin) tehlikesini taşır.</p>
<p><strong>yanıt değişkeninin birimi başına açıklayıcı değişkenin birimidir</strong> (Bu örnekte: Dolar/Dolar).</p>
<p>Ölçek değişimi, katsayıları değiştirir ancak temel ilişkiyi değiştirmez. Örneğin, Amazon fiyatını sent cinsinden kullanırsak:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>textbooks <span class="ot">&lt;-</span> textbooks <span class="sc">|&gt;</span> <span class="fu">mutate</span>(<span class="at">amaz_new_cents =</span> amaz_new <span class="sc">*</span> <span class="dv">100</span>) </span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(ucla_new <span class="sc">~</span> amaz_new_cents, <span class="at">data =</span> textbooks)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = ucla_new ~ amaz_new_cents, data = textbooks)

Coefficients:
   (Intercept)  amaz_new_cents  
       0.92897         0.01199  </code></pre>
</div>
</div>
<ul>
<li><strong>Eğim:</strong> <span class="math inline">\(\approx 0.01199\)</span> *</li>
</ul>
<p><strong>Yorum:</strong> Amazon fiyatındaki <strong>her bir ek centlik artış</strong>,</p>
<p>UCLA fiyatında <strong>ortalama $0.01199 (yaklaşık 1.2 cent)</strong> artışa neden olur. Temel ilişki (<span class="math inline">\(1.20\)</span> katı) korunmuştur.</p>
</section>
<section id="yorumlama-hataları" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="yorumlama-hataları"><span class="header-section-number">4</span> 🚨 Yorumlama Hataları</h2>
<p>Regresyon modelinin yorumlanmasında sık yapılan hatalar şunlardır:</p>
<ul>
<li><p><strong>Nedensellik İması:</strong> Regresyon, yalnızca bir <strong>ilişki</strong> veya <strong>ilişkilendirme</strong> gösterir, <strong>neden-sonuç</strong> ilişkisini kanıtlamaz.</p></li>
<li><p><strong>Değişken Rollerinin Değiştirilmesi:</strong> Eğim, <span class="math inline">\(x\)</span>’teki değişime karşılık <span class="math inline">\(y\)</span>’deki ortalama değişimi gösterir. <span class="math inline">\(y\)</span>’deki değişime karşılık <span class="math inline">\(x\)</span>’teki değişimi göstermez.</p></li>
<li><p><strong>Yüzde Değişim vs.&nbsp;Yüzde Puan Değişimi:</strong> Yüzde (örneğin, bir değişkenin %50’si) ile yüzde puanı (örneğin, %10’dan %12’ye 2 yüzde puanı artış) karıştırılmamalıdır, özellikle oranlar söz konusu olduğunda.</p></li>
</ul>
</section>
<section id="basit-lineer-modelleri-kurmak" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="basit-lineer-modelleri-kurmak"><span class="header-section-number">5</span> 🛠️ Basit Lineer Modelleri Kurmak</h2>
<p><strong>R</strong>’da bir regresyon modelini oluşturmak için <code>lm()</code> kullanılır.</p>
<p>Örnek 1: ODOKUMA1 (okuma puanlarının) OKUMA_ZEVK bir fonksiyonu olarak (midiPISA veri kümesi) lm(ODOKUMA1 ~ OKUMA_ZEVK, data = midiPISA)</p>
<p><code>lm()</code>, <code>coef()</code>, <code>summary()</code>, <code>fitted.values()</code>, <code>residuals()</code>, <code>predict()</code>, <code>augment()</code></p>
<p><code>lm()</code> fonksiyonunun çıktısı, <code>lm</code> sınıfından bir <strong>model nesnesidir</strong> (<code>books_mod</code>). Bu nesne, model hakkındaki tüm bilgileri depolar.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>books_mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(ucla_new <span class="sc">~</span> amaz_new, <span class="at">data =</span> textbooks) </span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(books_mod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "lm"</code></pre>
</div>
</div>
<p>Katsayılar (<code>coef()</code>) Sadece kesişim ve eğim katsayılarını bir vektör olarak döndürür</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(books_mod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)    amaz_new 
  0.9289651   1.1990014 </code></pre>
</div>
</div>
<p>Modelin tamamına ait istatistiksel çıktı</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(books_mod) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = ucla_new ~ amaz_new, data = textbooks)

Residuals:
    Min      1Q  Median      3Q     Max 
-34.785  -4.574   0.577   4.012  39.002 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  0.92897    1.93538    0.48    0.633    
amaz_new     1.19900    0.02519   47.60   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 10.47 on 71 degrees of freedom
Multiple R-squared:  0.9696,    Adjusted R-squared:  0.9692 
F-statistic:  2266 on 1 and 71 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Orijinal veri kümesindeki her bir gözlem için modelin tahmin ettiği <span class="math inline">\(\hat{y}\)</span> (yordanmıs değerleri) döndürür.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">fitted.values</span>(books_mod) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        1         2         3         4         5         6         7         8 
 34.44105  38.26587  39.29701  14.74146  17.96678  13.12281  24.98093  20.90433 
        9        10        11        12        13        14        15        16 
128.32287  16.82772  36.83906 106.54900  23.05054  20.67652 117.68772  57.89352 
       17        18        19        20        21        22        23        24 
 90.77014 160.12038 146.60764 130.42112  14.92131  23.63805  15.60474  27.24705 
       25        26        27        28        29        30        31        32 
 38.26587  35.64006  20.29284  46.19127  39.03323  40.46004  37.94214 102.84409 
       33        34        35        36        37        38        39        40 
 42.83406 118.37115  98.26390  12.31948  13.15878 162.42247 173.28542 211.95321 
       41        42        43        44        45        46        47        48 
181.53455 175.26377 209.02765 157.99815 189.98751 165.39599  30.84405 191.90591 
       49        50        51        52        53        54        55        56 
 28.58993  26.15595  52.10235  48.13365 103.08389 112.59197  81.74166 160.14436 
       57        58        59        60        61        62        63        64 
 30.07669  30.84405 103.38364  13.01490  79.73933 101.95682  11.24038  70.97463 
       65        66        67        68        69        70        71        72 
 97.29271  77.77297  45.33998  25.16078  48.09768  32.54663  29.93281  23.37427 
       73 
 22.77477 </code></pre>
</div>
</div>
<p>Gerçek <span class="math inline">\(y\)</span> değerleri ile tahmin edilen <span class="math inline">\(\hat{y}\)</span> değerleri arasındaki farkları (<span class="math inline">\(e_i = y_i - \hat{y}_i\)</span>) döndürür. <strong>En küçük kareler yöntemi</strong> ile oluşturulan modelde, artıkların ortalaması her zaman sıfırdır (teknik olarak sıfıra çok yakındır).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">residuals</span>(books_mod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           1            2            3            4            5            6 
 -6.77105468   2.32413081  -7.61701041   1.25853860   0.98322479   1.82719051 
           7            8            9           10           11           12 
 -0.28093350  -1.40432868  -4.48286560   0.17227613  -5.20905751   9.45100013 
          13           14           15           16           17           18 
  4.61945878   4.02348159   8.98227697  -3.99352239  -1.04014123  10.87961683 
          19           20           21           22           23           24 
  5.39236280  -5.62111808   1.07868839   2.31194809   2.39525758  -5.51704618 
          25           26           27           28           29           30 
  2.32413081  -6.69005609  -0.34283796   3.25873144   2.05676990  10.48995821 
          31           32           33           34           35           36 
  6.55786119 -20.39408550  -8.23406459 -29.95115384 -14.26390008  -1.06947854 
          37           38           39           40           41           42 
  1.84122047  17.60753411   0.71458128 -23.37321441 -34.78454847   8.48622894 
          43           44           45           46           47           48 
  5.47234904  39.00184934   4.01249154  10.85401060  -6.14405043  -3.90591073 
          49           50           51           52           53           54 
  1.11007224   0.08404511   3.02765446  -4.57365085  26.51611422  11.24803299 
          55           56           57           58           59           60 
  3.37833944  -7.66436320  -0.37668952  -6.14405043 -13.67363613  -2.51489936 
          61           62           63           64           65           66 
 13.14067180  -1.07682445   0.70962274   1.49537216  -5.19270894   0.57703413 
          67           68           69           70           71           72 
 -3.33997755  -6.41078371   0.36231919   7.00336756  -0.28280935   0.38572840 
          73 
  4.92522911 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(<span class="fu">residuals</span>(books_mod))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -5.944398e-17</code></pre>
</div>
</div>
<p><code>broom</code> paketindeki <code>augment()</code> fonksiyonu, orijinal veriyi uyarlanmış değerler, artıklar ve diğer model teşhis bilgileriyle birlikte içeren düzenli bir veri çerçevesi (<code>data.frame</code>) döndürür. Bu, model çıktılarını <strong>tidyverse</strong> ortamında analiz etmeyi kolaylaştırır.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'broom' was built under R version 4.4.3</code></pre>
</div>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">augment</span>(books_mod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["ucla_new"],"name":[1],"type":["dbl"],"align":["right"]},{"label":["amaz_new"],"name":[2],"type":["dbl"],"align":["right"]},{"label":[".fitted"],"name":[3],"type":["dbl"],"align":["right"]},{"label":[".resid"],"name":[4],"type":["dbl"],"align":["right"]},{"label":[".hat"],"name":[5],"type":["dbl"],"align":["right"]},{"label":[".sigma"],"name":[6],"type":["dbl"],"align":["right"]},{"label":[".cooksd"],"name":[7],"type":["dbl"],"align":["right"]},{"label":[".std.resid"],"name":[8],"type":["dbl"],"align":["right"]}],"data":[{"1":"27.67","2":"27.95","3":"34.44105","4":"-6.77105468","5":"0.01944321","6":"10.515199","7":"4.226829e-03","8":"-0.652942233"},{"1":"40.59","2":"31.14","3":"38.26587","4":"2.32413081","5":"0.01833896","6":"10.543185","7":"4.686540e-04","8":"0.223993081"},{"1":"31.68","2":"32.00","3":"39.29701","4":"-7.61701041","5":"0.01806141","6":"10.506820","7":"4.954865e-03","8":"-0.734001929"},{"1":"16.00","2":"11.52","3":"14.74146","4":"1.25853860","5":"0.02699567","6":"10.545810","7":"2.059099e-04","8":"0.121832728"},{"1":"18.95","2":"14.21","3":"17.96678","4":"0.98322479","5":"0.02554530","6":"10.546241","7":"1.185695e-04","8":"0.095110137"},{"1":"14.95","2":"10.17","3":"13.12281","4":"1.82719051","5":"0.02775510","6":"10.544587","7":"4.469293e-04","8":"0.176950099"},{"1":"24.70","2":"20.06","3":"24.98093","4":"-0.28093350","5":"0.02268020","6":"10.546858","7":"8.543980e-06","8":"-0.027135635"},{"1":"19.50","2":"16.66","3":"20.90433","4":"-1.40432868","5":"0.02429719","6":"10.545543","7":"2.294765e-04","8":"-0.135757804"},{"1":"123.84","2":"106.25","3":"128.32287","4":"-4.48286560","5":"0.02636508","6":"10.532925","7":"2.548167e-03","8":"-0.433822889"},{"1":"17.00","2":"13.26","3":"16.82772","4":"0.17227613","5":"0.02604795","6":"10.546892","7":"3.715594e-06","8":"0.016669061"},{"1":"31.63","2":"29.95","3":"36.83906","4":"-5.20905751","5":"0.01873712","6":"10.528168","7":"2.407299e-03","8":"-0.502135911"},{"1":"116.00","2":"88.09","3":"106.54900","4":"9.45100013","5":"0.01844092","6":"10.485102","7":"7.794440e-03","8":"0.910907676"},{"1":"27.67","2":"18.45","3":"23.05054","4":"4.61945878","5":"0.02342922","6":"10.532103","7":"2.390079e-03","8":"0.446369024"},{"1":"24.70","2":"16.47","3":"20.67652","4":"4.02348159","5":"0.02439150","6":"10.535669","7":"1.891346e-03","8":"0.388972632"},{"1":"126.67","2":"97.38","3":"117.68772","4":"8.98227697","5":"0.02201788","6":"10.490892","7":"8.467715e-03","8":"0.867312889"},{"1":"53.90","2":"47.51","3":"57.89352","4":"-3.99352239","5":"0.01452488","6":"10.535947","7":"1.087459e-03","8":"-0.384138738"},{"1":"89.73","2":"74.93","3":"90.77014","4":"-1.04014123","5":"0.01508321","6":"10.546168","7":"7.669359e-05","8":"-0.100080014"},{"1":"171.00","2":"132.77","3":"160.12038","4":"10.87961683","5":"0.04479266","6":"10.462654","7":"2.649222e-02","8":"1.062966531"},{"1":"152.00","2":"121.50","3":"146.60764","4":"5.39236280","5":"0.03596727","6":"10.526465","7":"5.130524e-03","8":"0.524430605"},{"1":"124.80","2":"108.00","3":"130.42112","4":"-5.62111808","5":"0.02733028","6":"10.524889","7":"4.161390e-03","8":"-0.544245474"},{"1":"16.00","2":"11.67","3":"14.92131","4":"1.07868839","5":"0.02691259","6":"10.546103","7":"1.507729e-04","8":"0.104417885"},{"1":"25.95","2":"18.94","3":"23.63805","4":"2.31194809","5":"0.02319808","6":"10.543206","7":"5.924816e-04","8":"0.223372468"},{"1":"18.00","2":"12.24","3":"15.60474","4":"2.39525758","5":"0.02659926","6":"10.542920","7":"7.342945e-04","8":"0.231825498"},{"1":"21.73","2":"21.95","3":"27.24705","4":"-5.51704618","5":"0.02183919","6":"10.525817","7":"3.167444e-03","8":"-0.532667629"},{"1":"40.59","2":"31.14","3":"38.26587","4":"2.32413081","5":"0.01833896","6":"10.543185","7":"4.686540e-04","8":"0.223993081"},{"1":"28.95","2":"28.95","3":"35.64006","4":"-6.69005609","5":"0.01908438","6":"10.515966","7":"4.047193e-03","8":"-0.645013417"},{"1":"19.95","2":"16.15","3":"20.29284","4":"-0.34283796","5":"0.02455128","6":"10.546831","7":"1.382683e-05","8":"-0.033146791"},{"1":"49.45","2":"37.75","3":"46.19127","4":"3.25873144","5":"0.01642563","6":"10.539598","7":"8.220236e-04","8":"0.313761594"},{"1":"41.09","2":"31.78","3":"39.03323","4":"2.05676990","5":"0.01813160","6":"10.543994","7":"3.627276e-04","8":"0.198204669"},{"1":"50.95","2":"32.97","3":"40.46004","4":"10.48995821","5":"0.01775864","6":"10.470767","7":"9.234223e-03","8":"1.010693480"},{"1":"44.50","2":"30.87","3":"37.94214","4":"6.55786119","5":"0.01842786","6":"10.517198","7":"3.750028e-03","8":"0.632056531"},{"1":"82.45","2":"85.00","3":"102.84409","4":"-20.39408550","5":"0.01747249","6":"10.256218","7":"3.432050e-02","8":"-1.964656784"},{"1":"34.60","2":"34.95","3":"42.83406","4":"-8.23406459","5":"0.01717439","6":"10.500089","7":"5.495873e-03","8":"-0.793105302"},{"1":"88.42","2":"97.95","3":"118.37115","4":"-29.95115384","5":"0.02226987","6":"9.906067","7":"9.527663e-02","8":"-2.892403464"},{"1":"84.00","2":"81.18","3":"98.26390","4":"-14.26390008","5":"0.01642800","6":"10.405876","7":"1.575174e-02","8":"-1.373377806"},{"1":"11.25","2":"9.50","3":"12.31948","4":"-1.06947854","5":"0.02813984","6":"10.546115","7":"1.553595e-04","8":"-0.103591709"},{"1":"15.00","2":"10.20","3":"13.15878","4":"1.84122047","5":"0.02773800","6":"10.544551","7":"4.535234e-04","8":"0.178307230"},{"1":"180.03","2":"134.69","3":"162.42247","4":"17.60753411","5":"0.04644271","6":"10.324375","7":"7.219393e-02","8":"1.721789118"},{"1":"174.00","2":"143.75","3":"173.28542","4":"0.71458128","5":"0.05480443","6":"10.546547","7":"1.428089e-04","8":"0.070185211"},{"1":"188.58","2":"176.00","3":"211.95321","4":"-23.37321441","5":"0.09227679","6":"10.131120","7":"2.789344e-01","8":"-2.342591363"},{"1":"146.75","2":"150.63","3":"181.53455","4":"-34.78454847","5":"0.06178867","6":"9.633991","7":"3.872219e-01","8":"-3.429184479"},{"1":"183.75","2":"145.40","3":"175.26377","4":"8.48622894","5":"0.05642951","6":"10.495096","7":"2.080974e-02","8":"0.834223429"},{"1":"214.50","2":"173.56","3":"209.02765","4":"5.47234904","5":"0.08902084","6":"10.524626","7":"1.464543e-02","8":"0.547487723"},{"1":"197.00","2":"131.00","3":"157.99815","4":"39.00184934","5":"0.04330931","6":"9.408665","7":"3.281620e-01","8":"3.807625635"},{"1":"194.00","2":"157.68","3":"189.98751","4":"4.01249154","5":"0.06951368","6":"10.535188","7":"5.893295e-03","8":"0.397204306"},{"1":"176.25","2":"137.17","3":"165.39599","4":"10.85401060","5":"0.04863716","6":"10.462711","7":"2.886263e-02","8":"1.062605267"},{"1":"24.70","2":"24.95","3":"30.84405","4":"-6.14405043","5":"0.02058913","6":"10.520777","7":"3.694004e-03","8":"-0.592825841"},{"1":"188.00","2":"159.28","3":"191.90591","4":"-3.90591073","5":"0.07134694","6":"10.535781","7":"5.754302e-03","8":"-0.387035126"},{"1":"29.70","2":"23.07","3":"28.58993","4":"1.11007224","5":"0.02136032","6":"10.546060","7":"1.252980e-04","8":"0.107150609"},{"1":"26.24","2":"21.04","3":"26.15595","4":"0.08404511","5":"0.02223896","6":"10.546908","7":"7.491239e-07","8":"0.008116166"},{"1":"55.13","2":"42.68","3":"52.10235","4":"3.02765446","5":"0.01532775","6":"10.540606","7":"6.606739e-04","8":"0.291350168"},{"1":"43.56","2":"39.37","3":"48.13365","4":"-4.57365085","5":"0.01603384","6":"10.532505","7":"1.579366e-03","8":"-0.440278767"},{"1":"129.60","2":"85.20","3":"103.08389","4":"26.51611422","5":"0.01753183","6":"10.050561","7":"5.822235e-02","8":"2.554497324"},{"1":"123.84","2":"93.13","3":"112.59197","4":"11.24803299","5":"0.02025756","6":"10.459091","7":"1.217296e-02","8":"1.085114173"},{"1":"85.12","2":"67.40","3":"81.74166","4":"3.37833944","5":"0.01406335","6":"10.539070","7":"7.527957e-04","8":"0.324887942"},{"1":"152.48","2":"132.79","3":"160.14436","4":"-7.66436320","5":"0.04480963","6":"10.505180","7":"1.315295e-02","8":"-0.748834637"},{"1":"29.70","2":"24.31","3":"30.07669","4":"-0.37668952","5":"0.02084707","6":"10.546814","7":"1.406665e-05","8":"-0.036350726"},{"1":"24.70","2":"24.95","3":"30.84405","4":"-6.14405043","5":"0.02058913","6":"10.520777","7":"3.694004e-03","8":"-0.592825841"},{"1":"89.71","2":"85.45","3":"103.38364","4":"-13.67363613","5":"0.01760665","6":"10.417222","7":"1.555083e-02","8":"-1.317334688"},{"1":"10.50","2":"10.08","3":"13.01490","4":"-2.51489936","5":"0.02780648","6":"10.542506","7":"8.483234e-04","8":"-0.243556130"},{"1":"92.88","2":"65.73","3":"79.73933","4":"13.14067180","5":"0.01392606","6":"10.427641","7":"1.127520e-02","8":"1.263623353"},{"1":"100.88","2":"84.26","3":"101.95682","4":"-1.07682445","5":"0.01725697","6":"10.546113","7":"9.446134e-05","8":"-0.103724115"},{"1":"11.95","2":"8.60","3":"11.24038","4":"0.70962274","5":"0.02866482","6":"10.546561","7":"6.975023e-05","8":"0.068753970"},{"1":"72.47","2":"58.42","3":"70.97463","4":"1.49537216","5":"0.01370489","6":"10.545377","7":"1.436283e-04","8":"0.143780724"},{"1":"92.10","2":"80.37","3":"97.29271","4":"-5.19270894","5":"0.01622822","6":"10.528333","7":"2.061341e-03","8":"-0.499921271"},{"1":"78.35","2":"64.09","3":"77.77297","4":"0.57703413","5":"0.01382264","6":"10.546684","7":"2.157564e-05","8":"0.055485410"},{"1":"42.00","2":"37.04","3":"45.33998","4":"-3.33997755","5":"0.01660691","6":"10.539227","7":"8.733758e-04","8":"-0.321613882"},{"1":"18.75","2":"20.21","3":"25.16078","4":"-6.41078371","5":"0.02261195","6":"10.518396","7":"4.435124e-03","8":"-0.619202108"},{"1":"48.46","2":"39.34","3":"48.09768","4":"0.36231919","5":"0.01604082","6":"10.546822","7":"9.915957e-06","8":"0.034878485"},{"1":"39.55","2":"26.37","3":"32.54663","4":"7.00336756","5":"0.02003375","6":"10.512962","7":"4.664804e-03","8":"0.675547942"},{"1":"29.65","2":"24.19","3":"29.93281","4":"-0.28280935","5":"0.02089596","6":"10.546857","7":"7.948256e-06","8":"-0.027291924"},{"1":"23.76","2":"18.72","3":"23.37427","4":"0.38572840","5":"0.02330152","6":"10.546809","7":"1.656937e-05","8":"0.037269724"},{"1":"27.70","2":"18.22","3":"22.77477","4":"4.92522911","5":"0.02353867","6":"10.530074","7":"2.730262e-03","8":"0.475941668"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fl">0.929</span> <span class="sc">+</span>   <span class="fl">1.199</span><span class="sc">*</span><span class="fl">27.95</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 34.44105</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a> <span class="fl">27.67</span> <span class="sc">-</span><span class="fl">34.44105</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -6.77105</code></pre>
</div>
</div>
<p>Modelimizi, orijinal veri setinde <strong>olmayan</strong> (“örneklem dışı”) yeni gözlemler için tahminler yapmak amacıyla kullanabiliriz. Bunun için <code>predict()</code> fonksiyonuna tahmin yapılacak yeni veriyi <code>newdata</code> argümanıyla bir veri çerçevesi olarak iletmeliyiz. Bu yeni veri çerçevesi, modelde kullanılan <strong>açıklayıcı değişkenle aynı isme</strong> sahip bir sütun içermelidir.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>new_data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">amaz_new =</span> <span class="fl">8.49</span>) </span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(books_mod, <span class="at">newdata =</span> new_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       1 
11.10849 </code></pre>
</div>
</div>
<p>Amazon fiyatı $8.49 olan bir kitap için UCLA fiyat tahmini: Çıktı: Beklenen fiyat yaklaşık $11.11</p>
<section id="regresyon-çizgisini-elle-ekleme" class="level3" data-number="5.1">
<h3 data-number="5.1" class="anchored" data-anchor-id="regresyon-çizgisini-elle-ekleme"><span class="header-section-number">5.1</span> Regresyon Çizgisini Elle Ekleme</h3>
<p><code>geom_smooth()</code> yerine <code>geom_abline()</code> ile de regresyon çizgisini bir serpilme grafiğine ekleyebiliriz.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>books_mod_coefs <span class="ot">&lt;-</span> <span class="fu">coef</span>(books_mod) <span class="sc">|&gt;</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">t</span>() <span class="sc">|&gt;</span></span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.data.frame</span>()</span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'ggplot2' was built under R version 4.4.3</code></pre>
</div>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> textbooks, <span class="fu">aes</span>(<span class="at">x =</span> amaz_new, <span class="at">y =</span> ucla_new )) <span class="sc">+</span> </span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> </span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">data =</span> books_mod_coefs, </span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>              <span class="fu">aes</span>(<span class="at">intercept =</span> <span class="st">`</span><span class="at">(Intercept)</span><span class="st">`</span>, <span class="at">slope =</span> amaz_new), <span class="at">color =</span> <span class="st">"dodgerblue"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="04_Regresyon_02_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Regresyon modeli, <strong>en küçük kareler yöntemi</strong> kullanılarak, artıkların karelerinin toplamını (<strong>SSE</strong>) minimize eden çizgiyi bulur. Modelin ne kadar iyi çalıştığını ölçmenin temel yolu, tipik bir hatanın (artığın) büyüklüğüne bakmaktır.</p>
<p>Artıkların ortalaması her zaman sıfır olduğu için, modelin toplam hatasını ölçmek için <strong>artıkların karelerinin toplamı</strong> (<strong>SSE</strong>) kullanılır.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>books_mod <span class="sc">|&gt;</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">augment</span>() <span class="sc">|&gt;</span></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">SSE =</span> <span class="fu">sum</span>(.resid<span class="sc">^</span><span class="dv">2</span>),</span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">SSE_also =</span> (<span class="fu">n</span>() <span class="sc">-</span> <span class="dv">1</span>) <span class="sc">*</span> <span class="fu">var</span>(.resid))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["SSE"],"name":[1],"type":["dbl"],"align":["right"]},{"label":["SSE_also"],"name":[2],"type":["dbl"],"align":["right"]}],"data":[{"1":"7786.615","2":"7786.615"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<ul>
<li><strong>Yorum:</strong> SSE, modelin gözlemlerden ne kadar “saptığını” yakalayan tek bir sayıdır. Ancak birimleri karesi alınmış olduğundan yorumlanması zordur.</li>
</ul>
<p>Modelin tipik hatasını yanıt değişkeninin birimlerinde ölçen en yaygın yol <strong>ortalama hata kareleri toplamı kökü</strong> (<strong>RMSE</strong>) veya regresyon çıktısında görünen adıyla <strong>Artık Standart Hatası</strong>’dır. Bu, esasen artıkların standart sapmasıdır.</p>
<p><span class="math display">\[
RMSE = \sqrt{ \frac{\sum_i{e_i^2}}{d.f.} } = \sqrt{ \frac{SSE}{n-2} }
\]</span></p>
<ul>
<li><p><span class="math inline">\(n-2\)</span> terimi, basit regresyonda serbestlik derecesidir (iki katsayı, <span class="math inline">\(\hat{\beta}_0\)</span> ve <span class="math inline">\(\hat{\beta}_1\)</span>, tahmin edildiği için).</p></li>
<li><p><strong>Yorum:</strong> RMSE (veya Artık Standart Hatası), gözlemlenen yanıt değişkeni değeri ile modelin tahmin ettiği değer arasındaki <strong>tipik farkı</strong> (yanıltıcı mesafe) yanıt değişkeninin orijinal birimlerinde verir.</p></li>
</ul>
<p>R bir regresyon modelinin <code>summary()</code>’sini gösterdiğinde, “artık standart hatasını” (<strong>residual standard error</strong>) gösterir. Bu, RMSE’dir. Keseli sıçanlar için bu, modelimizin tahmin edilen vücut uzunluğunun tipik olarak gerçeğin yaklaşık <strong>3.57 santimetre</strong> yakınında olduğunu söyler.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>total_tail_mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(total_l <span class="sc">~</span> tail_l, <span class="at">data =</span> possum)  </span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(total_tail_mod) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = total_l ~ tail_l, data = possum)

Residuals:
    Min      1Q  Median      3Q     Max 
-9.2100 -2.3265  0.1792  2.7765  6.7900 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  41.0371     6.6568   6.165 1.43e-08 ***
tail_l        1.2443     0.1796   6.927 3.94e-10 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3.572 on 102 degrees of freedom
Multiple R-squared:   0.32, Adjusted R-squared:  0.3133 
F-statistic: 47.99 on 1 and 102 DF,  p-value: 3.935e-10</code></pre>
</div>
</div>
<p>Possom (Gövde Uzunluğu ~ Kuyruk Uzunluğu)cm<span class="math inline">\(\approx 3.57\)</span>T</p>
<p>Tahmin edilen gövde uzunluğu, gerçek değerden tipik olarak <span class="math inline">\(3.57\)</span> cm sapar.</p>
<p>Ders kitapları için artık standart hatası <strong>10.47</strong>’dir. Serpilme grafiğinden ders kitabı modelinin uygunluğunun keseli sıçan modelinin uygunluğundan çok daha iyi göründüğü halde, bu rakam o kadar da kullanışlı görünmüyor. Bu iki fikri uzlaştırmak bir sonraki konudur.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>books_mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(ucla_new <span class="sc">~</span> amaz_new, <span class="at">data =</span> textbooks) </span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(books_mod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = ucla_new ~ amaz_new, data = textbooks)

Residuals:
    Min      1Q  Median      3Q     Max 
-34.785  -4.574   0.577   4.012  39.002 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  0.92897    1.93538    0.48    0.633    
amaz_new     1.19900    0.02519   47.60   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 10.47 on 71 degrees of freedom
Multiple R-squared:  0.9696,    Adjusted R-squared:  0.9692 
F-statistic:  2266 on 1 and 71 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Ders Kitapları (UCLA ~ Amazon Fiyatı)$<span class="math inline">\(\approx 10.47\)</span></p>
<p>Tahmin edilen UCLA fiyatı, gerçek değerden tipik olarak <strong>$10.47</strong> sapar.</p>
</section>
</section>
<section id="model-uygunluğu" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="model-uygunluğu"><span class="header-section-number">6</span> Model Uygunluğu</h2>
<p>Farklı birimlere sahip modellerin uyumunu karşılaştırmak için <strong>birimsiz</strong> bir ölçüye ihtiyacımız var. Bu, <strong>Belirtme Katsayısı</strong> veya yaygın adıyla <span class="math inline">\(R^2\)</span>’dir.</p>
<p><span class="math inline">\(R^2\)</span>’yi anlamak için bir kıyaslama modeli hayal ederiz: <strong>Boş Model</strong>.</p>
<ul>
<li><p>Boş Model, açıklayıcı değişkeni kullanmadan yanıt değişkenini tahmin etmeniz gerekseydi seçeceğiniz modeldir.</p></li>
<li><p>Bu model, tüm gözlemler için <span class="math inline">\(\hat{y} = \bar{y}\)</span> tahminini yapar.</p></li>
<li><p>Bu modelin hatası (kare artıkların toplamı) <strong>Toplam Kareler Toplamı</strong> (<strong>SST</strong>) olarak adlandırılır. SST, yanıt değişkenindeki <strong>toplam değişkenliği</strong> ölçer.</p></li>
</ul>
<p><span class="math display">\[
SST = \sum_{i=1}^{n} (y_i - \bar{y})^2
\]</span></p>
<p><span class="math inline">\(R^2\)</span>, regresyon modelimizin (<span class="math inline">\(SSE\)</span>) hatasını, boş modelin (<span class="math inline">\(SST\)</span>) hatasına kıyasla ne kadar azalttığını gösterir.</p>
<p><span class="math display">\[
R^2 = 1 - \frac{SSE}{SST} = 1 - \frac{\text{Açıklanamayan Değişkenlik}}{\text{Toplam Değişkenlik}}
\]</span></p>
<ul>
<li><p><strong>Yorum:</strong> <span class="math inline">\(R^2\)</span>, <strong>yanıt değişkenindeki değişkenliğin modelimiz tarafından açıklanan oranıdır</strong> (yüzdesi).</p></li>
<li><p><span class="math inline">\(R^2\)</span> değeri <strong>0</strong> ile <strong>1</strong> arasında değişir.</p>
<ul>
<li><p><span class="math inline">\(R^2=0\)</span>: Modelimiz, boş modelden daha iyi değildir (hiçbir değişkenliği açıklamaz).</p></li>
<li><p><span class="math inline">\(R^2=1\)</span>: Modelimiz, yanıttaki değişkenliğin tamamını açıklar (tüm noktalar çizgidedir).</p></li>
</ul></li>
<li><p><strong>Örnekler:</strong></p>
<ul>
<li><p>Possom Modeli (<span class="math inline">\(R^2 \approx 0.32\)</span>): Gövde uzunluğundaki değişkenliğin <strong>%32</strong>’si kuyruk uzunluğu ile açıklanır.</p></li>
<li><p>Ders Kitabı Modeli (<span class="math inline">\(R^2 \approx 0.97\)</span>): UCLA fiyatındaki değişkenliğin <strong>%97</strong>’si Amazon fiyatı ile açıklanır.</p></li>
</ul></li>
</ul>
<blockquote class="blockquote">
<p><span class="math inline">\(R^2\)</span> ve Korelasyon: Tek bir açıklayıcı değişkenli basit doğrusal regresyonda, <span class="math inline">\(R^2\)</span> değeri, korelasyon katsayısının karesine eşittir (<span class="math inline">\(R^2 = r_{x, y}^2\)</span>).</p>
</blockquote>
</section>
<section id="kaldıraç-leverage-ve-etki-influence" class="level2" data-number="7">
<h2 data-number="7" class="anchored" data-anchor-id="kaldıraç-leverage-ve-etki-influence"><span class="header-section-number">7</span> Kaldıraç (Leverage) ve Etki (Influence)</h2>
<p>Regresyon analizinde, bazı gözlemler modelin eğimini diğerlerinden daha fazla etkileyebilir. Bu noktaları incelemek için iki ana kavram kullanılır: <strong>Kaldıraç</strong> ve <strong>Etki</strong>.</p>
<section id="kaldıraç-leverage" class="level3" data-number="7.1">
<h3 data-number="7.1" class="anchored" data-anchor-id="kaldıraç-leverage"><span class="header-section-number">7.1</span> 1. Kaldıraç (Leverage)</h3>
<ul>
<li><p><strong>Tanım:</strong> Bir gözlemin <strong>kaldıracı</strong>, yalnızca bağımsız değişkenin (<span class="math inline">\(x\)</span>) değerine bağlıdır. Bir noktanın <strong>bağımsız</strong> <strong>değişkenin ortalamasından ne kadar uzak</strong> olduğunu ölçer.</p></li>
<li><p><span class="math inline">\(x\)</span> ekseni boyunca merkezden uzak olan noktalar <strong>yüksek kaldıraca</strong> sahiptir.</p></li>
<li><p>Kaldıraç, <code>augment()</code> çıktısındaki <strong><code>.hat</code></strong> sütununda bulunur.</p></li>
</ul>
</section>
<section id="etki-influence" class="level3" data-number="7.2">
<h3 data-number="7.2" class="anchored" data-anchor-id="etki-influence"><span class="header-section-number">7.2</span> 2. Etki (Influence)</h3>
<ul>
<li><p><strong>Tanım:</strong> Bir gözlemin <strong>etkisi</strong>, regresyon çizgisinin eğimini ne kadar değiştirdiğini ölçer.</p></li>
<li><p>Yüksek etki, hem <strong>yüksek kaldıraç</strong> hem de <strong>büyük bir artık</strong> (model çizgisinden dikey olarak uzaklık) kombinasyonunu gerektirir.</p></li>
</ul>
</section>
<section id="cook-mesafesi-cooks-distance" class="level3" data-number="7.3">
<h3 data-number="7.3" class="anchored" data-anchor-id="cook-mesafesi-cooks-distance"><span class="header-section-number">7.3</span> 3. Cook Mesafesi (Cook’s Distance)</h3>
<ul>
<li><p><strong>Tanım:</strong> Kaldıraç ve artığı birleştirerek <strong>etkiyi</strong> ölçen tek bir sayıdır.</p></li>
<li><p><strong>Yorum:</strong> Yüksek Cook mesafesi, noktanın modelin eğimini önemli ölçüde değiştirdiğini gösterir.</p></li>
<li><p>Cook mesafesi, <code>augment()</code> çıktısındaki <strong><code>.cooksd</code></strong> sütununda bulunur.</p>
<ul>
<li><p>Örnek: Bir şehirde ev fiyatını (<strong>Y</strong>) evin büyüklüğüne (<strong>X = m²</strong>) göre tahmin eden basit bir doğrusal regresyon düşünelim.</p>
<p>Çoğu ev 100–200 m² aralığında, ancak <strong>bir tane çok büyük ev (örneğin 400 m²)</strong> var:</p></li>
<li><p>Bu ev, <strong>yüksek kaldıraçlı</strong> olur (çünkü x ekseninde uçtadır).</p></li>
</ul></li>
<li><p>Eğer bu evin fiyatı beklenenden çok farklıysa (çok ucuz veya çok pahalıysa), <strong>yüksek etkili (influential)</strong> hale gelir</p></li>
</ul>
<pre><code>::: {.cell}

```{.r .cell-code}
library(tidyverse)
```

::: {.cell-output .cell-output-stderr}

```
Warning: package 'purrr' was built under R version 4.4.3
```


:::

::: {.cell-output .cell-output-stderr}

```
── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ lubridate 1.9.4     ✔ tibble    3.2.1
✔ purrr     1.0.4     ✔ tidyr     1.3.1
✔ readr     2.1.5     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors
```


:::

```{.r .cell-code}
library(broom)  # Veri oluşturalım set# Gerekli paketler
library(tidyverse)
library(broom)

# Veri oluşturalım
set.seed(123)
data &lt;- tibble(
  size = c(runif(20, 100, 200), 400),  # son ev çok büyük: 400 m²
  price = c(2000 + 15 * runif(20, 100, 200),  # ortalama ilişki
            2000 + 15 * 400 + 50000)           # büyük ev beklenenden pahalı
)

# Modeli kuralım
model &lt;- lm(price ~ size, data = data)

# Kaldıraç (.hat) ve etki (Cook's distance) ekleyelim
aug &lt;- augment(model)

# Veriye ekleyelim

# Grafik: kaldıraç ve etki gösterimi
ggplot(aug, aes(x = size, y = price)) +
  geom_point(aes(size = .hat, color = .cooksd)) +
  geom_smooth(method = "lm", se = FALSE, color = "blue") +
  scale_color_gradient(low = "gray70", high = "red") +
  labs(
    title = "Kaldıraç ve Etki (Leverage &amp; Influence) Örneği",
    subtitle = "Büyük kırmızı nokta = yüksek kaldıraca ve yüksek etkiye sahip gözlem",
    x = "Ev Büyüklüğü (m²)",
    y = "Ev Fiyatı",
    color = "Cook's Distance\n(Etki)",
    size = "Leverage\n(Kaldıraç)"
  ) +
  theme_minimal()
```

::: {.cell-output .cell-output-stderr}

```
`geom_smooth()` using formula = 'y ~ x'
```


:::

::: {.cell-output-display}
![](04_Regresyon_02_files/figure-html/unnamed-chunk-21-1.png){width=672}
:::
:::



::: {.cell}

```{.r .cell-code}
plot(model, which = 4)
```

::: {.cell-output-display}
![](04_Regresyon_02_files/figure-html/unnamed-chunk-22-1.png){width=672}
:::
:::</code></pre>
</section>
</section>
<section id="aykırı-değerlerle-başa-çıkma" class="level2" data-number="8">
<h2 data-number="8" class="anchored" data-anchor-id="aykırı-değerlerle-başa-çıkma"><span class="header-section-number">8</span> 🗑️ Aykırı Değerlerle Başa Çıkma</h2>
<p>Etkili bir gözlemin modelinizin bilimsel değerini azalttığını belirlerseniz, ne yapabilirsiniz?</p>
<ul>
<li><p><strong>Çözüm:</strong> En bariz çözüm, aykırı değeri veri kümesinden <strong>çıkarmaktır</strong>.</p></li>
<li><p><strong>Ancak:</strong> Bu kararı verirken <strong>bilimsel dürüstlükle</strong> hareket etmeli ve kendinize şu soruları sormalısınız:</p>
<ol type="1">
<li><p><strong>Gerekçe nedir?</strong> Gözlemi kaldırmak için bilimsel veya mantıksal bir gerekçeniz var mı (örn. hatalı veri girişi, gözlemin ait olmadığı bir popülasyondan gelmesi)? <strong>“Sonuçlarımı iyileştirdiği için” iyi bir gerekçe değildir.</strong></p></li>
<li><p><strong>Çıkarım Kapsamı Nasıl Değişir?</strong> Aykırı değeri kaldırdığınızda, modelinizin sonuçları artık popülasyonun hangi alt kümesi için geçerlidir? (Örn. en zengin ülkeyi çıkarırsanız, sonuçlarınız artık <strong>en zengin ülkeler</strong> için geçerli olmaz.)</p></li>
</ol></li>
<li></li>
</ul>
</section>
<section id="model-uygunluklarını-karşılaştırma" class="level2" data-number="9">
<h2 data-number="9" class="anchored" data-anchor-id="model-uygunluklarını-karşılaştırma"><span class="header-section-number">9</span> Model Uygunluklarını Karşılaştırma</h2>
<section id="boş-ortalama-model" class="level3" data-number="9.1">
<h3 data-number="9.1" class="anchored" data-anchor-id="boş-ortalama-model"><span class="header-section-number">9.1</span> Boş (Ortalama) Model</h3>
<p>Model uygunluğunun kalitesini karşılaştırmanın bir yolu, <strong>birimsiz</strong> bir karşılaştırma yolu bulmaktır. Bunu yapmak için bir karşılaştırma noktası düşünmek faydalıdır.</p>
<p>Eğer bir keseli sıçanın vücut uzunluğunu tahmin etmek zorunda olsaydınız ve o keseli sıçan hakkında hiçbir bilginiz olmasaydı, tahmininiz ne olurdu?</p>
<p>Mantıklı bir seçim, tüm keseli sıçanların <strong>ortalama</strong> uzunluğu olacaktır. Bu, <span class="math inline">\(\hat{y} = \bar{y}\)</span> olduğu bir model olarak düşünülebilir. Bu modele genellikle <strong>boş model</strong> (<strong>null model</strong>) denir. Bu modeli bir karşılaştırma noktası olarak kullanmak mantıklıdır, çünkü yapılması hiçbir içgörü gerektirmez ve daha kötü olabilecek makul bir model yoktur.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>null_mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(total_l <span class="sc">~</span> <span class="dv">1</span>, <span class="at">data =</span> possum)</span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>null_mod <span class="sc">|&gt;</span></span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">augment</span>() <span class="sc">|&gt;</span></span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">tail_l =</span> possum<span class="sc">$</span>tail_l) <span class="sc">|&gt;</span></span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> tail_l, <span class="at">y =</span> total_l)) <span class="sc">+</span></span>
<span id="cb44-7"><a href="#cb44-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="dv">0</span>, <span class="at">formula =</span> y <span class="sc">~</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb44-8"><a href="#cb44-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_segment</span>(<span class="fu">aes</span>(<span class="at">xend =</span> tail_l, <span class="at">yend =</span> .fitted),</span>
<span id="cb44-9"><a href="#cb44-9" aria-hidden="true" tabindex="-1"></a>               <span class="at">arrow =</span> <span class="fu">arrow</span>(<span class="at">length =</span> <span class="fu">unit</span>(<span class="fl">0.15</span>, <span class="st">"cm"</span>)),</span>
<span id="cb44-10"><a href="#cb44-10" aria-hidden="true" tabindex="-1"></a>               <span class="at">color =</span> <span class="st">"darkgray"</span>) <span class="sc">+</span></span>
<span id="cb44-11"><a href="#cb44-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="04_Regresyon_02_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Boş modelin SSE’si, genellikle <strong>SST</strong> (Toplam Kareler Toplamı, <em>S</em>um of <em>S</em>quares <em>T</em>otal) olarak adlandırılır. Bu, yanıt değişkenindeki değişkenliğin bir ölçüsüdür. Bu değer 1913.826’dır.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>null_mod <span class="sc">|&gt;</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a><span class="fu">augment</span>(possum) <span class="sc">|&gt;</span></span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summarize</span>(<span class="at">SST =</span> <span class="fu">sum</span>(.resid<span class="sc">^</span><span class="dv">2</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["SST"],"name":[1],"type":["dbl"],"align":["right"]}],"data":[{"1":"1913.826"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<p>Bu sayıyı, kuyruk uzunluğunu açıklayıcı değişken olarak kullanan keseli sıçan modelimizin SSE’si ile karşılaştırın. Bu durumda SSE, 1301.488’dir.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>total_tail_mod <span class="sc">|&gt;</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a><span class="fu">augment</span>() <span class="sc">|&gt;</span></span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summarize</span>(<span class="at">SSE =</span> <span class="fu">sum</span>(.resid<span class="sc">^</span><span class="dv">2</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["SSE"],"name":[1],"type":["dbl"],"align":["right"]}],"data":[{"1":"1301.488"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<p>Modelimizin SSE’sinin boş modelin SSE’sine oranı, modelimiz tarafından açıklanan değişkenliğin bir ölçüsüdür. Bu fikirler, genellikle <span class="math inline">\(\mathbf{R^2}\)</span> olarak anılan “belirleme katsayısı” formülü ile yakalanır:</p>
<p><span class="math display">\[R^2 = 1 - \frac{SSE}{SST} = 1 - \frac{Var(e)}{Var(y)}
\]</span>Bu tanımdan dolayı, <span class="math inline">\(R^2\)</span>’yi, yanıt değişkenindeki değişkenliğin modelimiz tarafından açıklanan <strong>oranı</strong> olarak yorumlarız. Bu, bir regresyon modelinin uygunluk kalitesinin en sık belirtilen ölçüsüdür.</p>
<p>Tek bir açıklayıcı değişkenli en küçük kareler regresyon modelleri için, <span class="math inline">\(R^2\)</span> değeri, korelasyon katsayısının karesidir (<span class="math inline">\(r_{x, y}^2\)</span>).</p>
<p><span class="math inline">\(R^2\)</span> değerini görmenin en kolay yolu, model nesnenize <code>summary()</code> işlevini uygulamaktır. Keseli sıçanlar için modelimiz, vücut uzunluğundaki değişkenliğin yaklaşık <strong>%32</strong>’sini açıklar.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(total_tail_mod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = total_l ~ tail_l, data = possum)

Residuals:
    Min      1Q  Median      3Q     Max 
-9.2100 -2.3265  0.1792  2.7765  6.7900 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  41.0371     6.6568   6.165 1.43e-08 ***
tail_l        1.2443     0.1796   6.927 3.94e-10 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3.572 on 102 degrees of freedom
Multiple R-squared:   0.32, Adjusted R-squared:  0.3133 
F-statistic: 47.99 on 1 and 102 DF,  p-value: 3.935e-10</code></pre>
</div>
</div>
<p>Ders kitapları için <span class="math inline">\(R^2\)</span> değeri çok daha yüksektir - <strong>%97</strong>’dir. Gerçekten de, <span class="math inline">\(R^2\)</span> karşılaştırması, ders kitabı modelinin ders kitabı verilerine keseli sıçan modelinin keseli sıçan verilerine olduğundan daha iyi oturduğu yönündeki grafiksel sezgimizi doğrulamaya yardımcı olur.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(books_mod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = ucla_new ~ amaz_new, data = textbooks)

Residuals:
    Min      1Q  Median      3Q     Max 
-34.785  -4.574   0.577   4.012  39.002 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  0.92897    1.93538    0.48    0.633    
amaz_new     1.19900    0.02519   47.60   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 10.47 on 71 degrees of freedom
Multiple R-squared:  0.9696,    Adjusted R-squared:  0.9692 
F-statistic:  2266 on 1 and 71 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Yüksek bir <span class="math inline">\(R^2\)</span> tek başına “iyi” bir modele sahip olduğunuz anlamına gelmez ve düşük bir <span class="math inline">\(R^2\)</span> “kötü” bir modele sahip olduğunuz anlamına gelmez. Düşük bir <span class="math inline">\(R^2\)</span>’li bir model, karmaşık bir problem hakkında önemli içgörüler sağlayabilir.</p>
<blockquote class="blockquote">
<p>“Esasen, tüm modeller yanlıştır, ancak bazıları kullanışlıdır” - George Box</p>
</blockquote>
</section>
<section id="r2-yorumu" class="level3" data-number="9.2">
<h3 data-number="9.2" class="anchored" data-anchor-id="r2-yorumu"><span class="header-section-number">9.2</span> <span class="math inline">\(R^2\)</span> Yorumu</h3>
<p>ABD eyaletlerindeki lise mezuniyet oranına göre yoksulluk oranı için regresyon modelinde bildirilen <span class="math inline">\(\mathbf{R^2}\)</span>, <strong>0.464</strong>’tür. Bu değer nasıl yorumlanmalıdır?</p>
<blockquote class="blockquote">
<p><strong>Cevap:</strong> ABD eyaletleri arasındaki yoksulluk oranındaki değişkenliğin <strong>%46.4</strong>’ü, lise mezuniyet oranı ile açıklanabilir.</p>
</blockquote>
</section>
</section>
<section id="olağandışı-noktalar" class="level2" data-number="10">
<h2 data-number="10" class="anchored" data-anchor-id="olağandışı-noktalar"><span class="header-section-number">10</span> Olağandışı Noktalar</h2>
<p>Daha önce, aykırı değerleri tanımlamayı öğrenmiştik. Şimdi, iki ilgili ama farklı kavramı tanıtarak bu anlayışı hassaslaştıracağız: <strong>Kaldıraç</strong> (<strong>Leverage</strong>) ve <strong>Etki</strong> (<strong>Influence</strong>).</p>
<p>Beyzbol oyuncularının çaldığı üs sayısı ile vurduğu home run sayısı arasındaki ilişkiyi inceleyen serpilme grafiğini hatırlayın.</p>
<section id="kaldıraç-leverage-1" class="level3" data-number="10.1">
<h3 data-number="10.1" class="anchored" data-anchor-id="kaldıraç-leverage-1"><span class="header-section-number">10.1</span> Kaldıraç (Leverage)</h3>
<p>Kaldıraç, bir gözlemin açıklayıcı değişkenin <span class="math inline">\((\mathbf{x})\)</span> ortalamasından ne kadar uzakta olduğunun bir fonksiyonudur. Yani, serpilme grafiğinin merkezine (x-ekseni boyunca) yakın olan noktalar düşük kaldıraçlı, uzakta olan noktalar ise <strong>yüksek kaldıraçlıdır</strong>. Kaldıraç için <span class="math inline">\(y\)</span>-koordinatı hiç önemli değildir. <span class="math display">\[
h_i = \frac{1}{n} + \frac{(x_i - \bar{x})^2}{\sum_{i=1}^n (x_i - \bar{x})^2}
\]</span> Yüksek kaldıraca sahip gözlemler, açıklayıcı değişkenin aşırı değerleri nedeniyle, regresyon doğrusunun eğimi üzerinde önemli bir etkiye sahip olabilir veya olmayabilir. Böyle bir etkiye sahip olan gözleme etkili (influential) denir.</p>
<p>Etki (Influence) - Cook’s MesafesiCook’s mesafesi olarak bilinen bir ölçüm, etkiyi ölçmek için bu iki niceliği (kaldıraç ve artık) birleştirir.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>regulars <span class="ot">&lt;-</span> mlbbat10 <span class="sc">|&gt;</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(at_bat <span class="sc">&gt;</span> <span class="dv">400</span>)</span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> regulars, <span class="fu">aes</span>(<span class="at">x =</span> stolen_base, <span class="at">y =</span> home_run)) <span class="sc">+</span></span>
<span id="cb51-5"><a href="#cb51-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb51-6"><a href="#cb51-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="04_Regresyon_02_files/figure-html/unnamed-chunk-28-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>mod_hr_sb <span class="ot">&lt;-</span> <span class="fu">lm</span>(home_run <span class="sc">~</span> stolen_base, <span class="at">data =</span> regulars)</span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a>mod_hr_sb <span class="sc">|&gt;</span></span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a><span class="fu">augment</span>() <span class="sc">|&gt;</span></span>
<span id="cb53-5"><a href="#cb53-5" aria-hidden="true" tabindex="-1"></a><span class="fu">select</span>(home_run, stolen_base, .fitted, .resid, .hat, .cooksd) <span class="sc">|&gt;</span></span>
<span id="cb53-6"><a href="#cb53-6" aria-hidden="true" tabindex="-1"></a><span class="fu">slice_max</span>(<span class="at">order_by =</span> .cooksd, <span class="at">n =</span> <span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["home_run"],"name":[1],"type":["dbl"],"align":["right"]},{"label":["stolen_base"],"name":[2],"type":["dbl"],"align":["right"]},{"label":[".fitted"],"name":[3],"type":["dbl"],"align":["right"]},{"label":[".resid"],"name":[4],"type":["dbl"],"align":["right"]},{"label":[".hat"],"name":[5],"type":["dbl"],"align":["right"]},{"label":[".cooksd"],"name":[6],"type":["dbl"],"align":["right"]}],"data":[{"1":"54","2":"9","3":"17.422632","4":"36.57737","5":"0.006071871","6":"0.04338485"},{"1":"19","2":"47","3":"7.735927","4":"11.26407","5":"0.055501875","6":"0.04164828"},{"1":"34","2":"26","3":"13.089106","4":"20.91089","5":"0.014354719","6":"0.03408782"},{"1":"42","2":"14","3":"16.148065","4":"25.85193","5":"0.006183536","6":"0.02207554"},{"1":"39","2":"0","3":"19.716851","4":"19.28315","5":"0.010752252","6":"0.02155489"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<p>Yüksek kaldıraç ve büyük artığın birleşimi etkiyi belirler.A</p>
<p>ykırı Değerlerle Başa ÇıkmakEtkili bir gözlemin regresyon doğrusunun eğimini modelinizin bilimsel değerini zayıflatacak şekilde etkilediğini belirlediğinizi varsayalım. Bu konuda ne yapabilirsiniz?Kısa cevap, aykırı değerleri çıkarmaktan başka yapabileceğiniz pek bir şey olmadığıdır. İstatistiksel modelleyici olarak bu bir karardır, ancak bu kararın sonuçlarını anlamanız ve iyi bir bilimsel inançla hareket etmeniz çok önemlidir.</p>
<p>Aykırı değerleri çıkarırken kendinize sormanız gereken ilk sorular şunlardır:</p>
<p>Gözlemi kaldırmak için gerekçe nedir? “Çünkü sonuçlarımı iyileştiriyor” iyi bir gerekçe değildir.Çıkarım kapsamı nasıl değişir? (Örn. En fakir ülkeleri çıkarırsanız, sonuçlarınız artık tüm ülkelere değil, sadece “fakir olmayan” ülkelere uygulanır.)</p>
<p>Aykırı değerlerin çıkarılması, bir modelin eğimini ve <span class="math inline">\(R^2\)</span> değerini önemli ölçüde değiştirebilir. Şeffaflık ve güçlü bilimsel gerekçe anahtardır.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/atalay-k\.github\.io\/2026_OLC731\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>