---
title: "📅 Haftalık İçerik"
format:
  html:
    toc: true
    toc-depth: 2
    number-sections: false
    code-fold: false
    df-print: paged
    sidebar: false
---

Aşağıda her haftaya ait içeriğe bağlantılar yer almaktadır. Başlıklar üzerine tıklayarak detaylara ulaşabilirsiniz.

## 🔹 [1-2. Hafta – Temeller](01_Giris.qmd)

-   Paketlerden veri yüklemek

-   Veri setlerini (data frame) tanıtmak

-   Değişken türleri tanıtmak

-   Veri setlerini değişken türlerini dönüştürmek için `mutate()` fonksiyonunu kullanmak

-   Sürekli değişkenleri kategorik değişkenlere dönüştürmek

-   Verileri filtrelemek ve ardından gereksiz düzeyleri (levels) kaldırmak

-   Kategorik değişkenlerde bazı düzeyleri birleştirmek

-   İki mevcut değişkene dayalı yeni bir değişken oluşturmak

## 🔹 [3. Hafta – Veri İnceleme](02_Veri_duz.qmd)

-   Verilerin düzenlenmesi, özetlenmesi ve görselleştirilmesi yoluyla farklı bakış açılarının nasıl elde edilebileceğini öğrenmek.

-   Yanıltıcı özet istatistiklerin önüne geçmek için verileri farklı açılardan incelemenin önemini kavramak.

------------------------------------------------------------------------

### 🔹 [4-5. Hafta – Keşfedici Veri Analizi- I](03_Kat.qmd)

------------------------------------------------------------------------

### 🔹 \[6-7. Hafta – Regresyon\]

### 🔹 \[9. Hafta – Regresyon\]

### 🔹 \[10. Hafta – Hipotez Testleri\]

------------------------------------------------------------------------

### 🔹 \[11. Hafta – İstatistiksel çıkarım I\]

------------------------------------------------------------------------

### 🔹 \[12. Hafta – Çıkarımsal Modelleme I\]

📌 **Not:** 9. hafta (Ara sınav) ve 16. hafta (Final sınavı) içerik sayfası olarak eklenmemiştir.
